### ISSUE TITLE
Batch transfer of ETH and ERC20 no longer possible in v1 beta

### ISSUE THREAD

**Issue by daveraine** [immutable/imx-core-sdk#202]
## Expected Behavior
The SDK should mirror the API functionality and allow batch transfers of ETH and ERC20 as in v0.6.0.

## Current Behavior
The SDK only provides `batchNftTransfer` for ERC721. ETH and ERC20 can now only be transferred individually using `transfer`. 

## Possible Solution
Add a `batchTransfer` function with functionality of `batchNftTransferWithSigner` from v0.6.0.

## Steps to Reproduce
1. Install `@imtbl/core-sdk@1.0.0-beta.3`
2. Attempt to write code to bulk transfer ETH or ERC20 tokens.

## Context (Environment)
I'm currently migrating our code base from v0.6.0 due to Ropsten being shut down soon and v0.6.0 does not support Goerli. We are using the `batchNftTransferWithSigner` workflow function to batch transfer any token type but this is now not possible.

## Detailed Description
Functionality to batch transfer any token type has been removed by the SDK but the API supports it. Furthermore it can't be worked around as access to `TransfersApi` and `Workflows` classes is no longer available due to #183, instead the `ImmutableX` class must be used that does not expose these.

**Comment by ckailash** [comment]
Thanks for raising this issue. We're reviewing the updated interface of the Core SDK v1.0.0-beta3 and will address your feedback as part of the v1.0 stable release.

**Comment by zatlite** [comment]
The only batch transfers supported by `TransfersApi` was for `ERC721` NFT tokens. If you tried to call `batchNftTransfer` method and pass in an `ETH` or `ERC20` token you would have received an error `multiple transfer request only available for ERC721 tokens`. 
v1 beta improved the SDK interface so that it is no longer possible to pass in the wrong token type and get the above error.

**Comment by daveraine** [comment]
Thanks for the information, I wasn't aware of this restriction on the previous SDK. I will close this issue.
