### ISSUE TITLE
include_fees is missing in the list orders request

### ISSUE THREAD

**Issue by t1nky** [immutable/imx-core-sdk#86]
`include_fees` query parameter is missing in the list orders request but actually working when sending the request (through postman, for example).

It is missing in the openapi schema file as well.

**Comment by CodeSchwert** [comment]
@t1nky we've confirmed on our end the `include_fees` query parameter does work with the order list endpoint and the updated documentation and OpenAPI spec will be released shortly, likely later today.

**Comment by CodeSchwert** [comment]
`include_fees` query param live on the docs: https://docs.x.immutable.com/reference/#/operations/listOrders

**Comment by t1nky** [comment]
Can confirm new version resolves the issue, thank you!
